-- AlterTable
ALTER TABLE "accounts" ADD COLUMN     "deletedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "models" ADD COLUMN     "deletedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "trades" ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "direction" TEXT NOT NULL DEFAULT 'LONG',
ALTER COLUMN "entryPrice" DROP NOT NULL,
ALTER COLUMN "entryPrice" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "exitPrice" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "stopLoss" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "takeProfit" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "quantity" SET DATA TYPE DECIMAL(20,8),
ALTER COLUMN "risk" SET DATA TYPE DECIMAL(12,2);

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "name" TEXT;
